# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dbservice.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'dbservice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64\x62service.proto\x12\tdbservice\x1a\x1bgoogle/protobuf/empty.proto\"%\n\x04Item\x12\r\n\x05input\x18\x01 \x01(\x0c\x12\x0e\n\x06output\x18\x02 \x01(\x0c\"\x0b\n\tEmptyData\"\x1f\n\nAddRequest\x12\x11\n\timg_bytes\x18\x01 \x01(\x0c\"\x19\n\x0b\x41\x64\x64Response\x12\n\n\x02id\x18\x01 \x01(\t\"6\n\tReadyData\x12\n\n\x02id\x18\x01 \x01(\t\x12\x1d\n\x04item\x18\x02 \x01(\x0b\x32\x0f.dbservice.Item\"\x9a\x01\n\x0cPullResponse\x12&\n\x06status\x18\x01 \x01(\x0e\x32\x16.dbservice.QueueStatus\x12\x0c\n\x02id\x18\x02 \x01(\tH\x00\x12%\n\x05\x65mpty\x18\x03 \x01(\x0b\x32\x14.dbservice.EmptyDataH\x00\x12%\n\x05ready\x18\x04 \x01(\x0b\x32\x14.dbservice.ReadyDataH\x00\x42\x06\n\x04\x64\x61ta\"3\n\x0f\x46inalizeRequest\x12\r\n\x05\x65rror\x18\x01 \x01(\x08\x12\x11\n\timg_bytes\x18\x02 \x01(\x0c\"\x1a\n\x0c\x43heckRequest\x12\n\n\x02id\x18\x01 \x01(\t\"f\n\x12\x43heckResponseExist\x12\x1f\n\x05state\x18\x01 \x01(\x0e\x32\x10.dbservice.State\x12\x1d\n\x04item\x18\x02 \x01(\x0b\x32\x0f.dbservice.Item\x12\x10\n\x08position\x18\x03 \x01(\x05\"n\n\rCheckResponse\x12%\n\x05\x65mpty\x18\x01 \x01(\x0b\x32\x14.dbservice.EmptyDataH\x00\x12.\n\x05\x65xist\x18\x02 \x01(\x0b\x32\x1d.dbservice.CheckResponseExistH\x00\x42\x06\n\x04\x64\x61ta*<\n\x05State\x12\x0c\n\x08PENDING1\x10\x00\x12\x0c\n\x08PENDING2\x10\x01\x12\x0b\n\x07SUCCESS\x10\x02\x12\n\n\x06\x46\x41ILED\x10\x03*3\n\x0bQueueStatus\x12\x0e\n\nPROCESSING\x10\x00\x12\t\n\x05\x45MPTY\x10\x01\x12\t\n\x05READY\x10\x02\x32\xf4\x01\n\tDBService\x12\x34\n\x03\x41\x64\x64\x12\x15.dbservice.AddRequest\x1a\x16.dbservice.AddResponse\x12\x35\n\x04Pull\x12\x14.dbservice.EmptyData\x1a\x17.dbservice.PullResponse\x12>\n\x08\x46inalize\x12\x1a.dbservice.FinalizeRequest\x1a\x16.google.protobuf.Empty\x12:\n\x05\x43heck\x12\x17.dbservice.CheckRequest\x1a\x18.dbservice.CheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dbservice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATE']._serialized_start=681
  _globals['_STATE']._serialized_end=741
  _globals['_QUEUESTATUS']._serialized_start=743
  _globals['_QUEUESTATUS']._serialized_end=794
  _globals['_ITEM']._serialized_start=59
  _globals['_ITEM']._serialized_end=96
  _globals['_EMPTYDATA']._serialized_start=98
  _globals['_EMPTYDATA']._serialized_end=109
  _globals['_ADDREQUEST']._serialized_start=111
  _globals['_ADDREQUEST']._serialized_end=142
  _globals['_ADDRESPONSE']._serialized_start=144
  _globals['_ADDRESPONSE']._serialized_end=169
  _globals['_READYDATA']._serialized_start=171
  _globals['_READYDATA']._serialized_end=225
  _globals['_PULLRESPONSE']._serialized_start=228
  _globals['_PULLRESPONSE']._serialized_end=382
  _globals['_FINALIZEREQUEST']._serialized_start=384
  _globals['_FINALIZEREQUEST']._serialized_end=435
  _globals['_CHECKREQUEST']._serialized_start=437
  _globals['_CHECKREQUEST']._serialized_end=463
  _globals['_CHECKRESPONSEEXIST']._serialized_start=465
  _globals['_CHECKRESPONSEEXIST']._serialized_end=567
  _globals['_CHECKRESPONSE']._serialized_start=569
  _globals['_CHECKRESPONSE']._serialized_end=679
  _globals['_DBSERVICE']._serialized_start=797
  _globals['_DBSERVICE']._serialized_end=1041
# @@protoc_insertion_point(module_scope)
